name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Build
        env:
          NODE_ENV: production
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
